### ISSUE TITLE
[Healthcheck] The CSS causes a layout shift of the Admin Menu / Left Navigation Items.

### ISSUE THREAD

**Issue by tim-breitenstein-it** [Smile-SA/elasticsuite#3543]
### Preconditions

- Ubuntu 22.04
- PHP 8.2
- MariaDB 10.6

Magento Version : v2.4.6-p9

ElasticSuite Version : 2.11.11

Environment : Developer and Production mode

Third party modules : 
- Magesuite : v13.0.0

### Steps to reproduce

1. Install ElasticSuite Version v2.11.11
2. Go to Healthcheck Page
3. See Admin Menu / Left Navigation Items

### Expected result

1. No layout shift.

![Image](https://github.com/user-attachments/assets/1ed59b7f-9e01-4f9d-b274-a872098f22e9)

### Actual result

1. Layout shift.

![Image](https://github.com/user-attachments/assets/b92023d3-020f-448c-baa9-36cae6f88552)

This CSS causes the issue:

https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-core/view/adminhtml/web/css/source/_module.less#L51

![Image](https://github.com/user-attachments/assets/e818a03c-7269-48a8-935b-274aa8b2b6eb)

**Comment by rbayet** [comment]
Hello @tim-breitenstein-it,

Yes, indeed, good catch, this is not as dramatic on my local environment (probably due to the Magesuite logo or your browser font size ?).

Regards,

**Comment by tim-breitenstein-it** [comment]
> your browser font size ?

```css
body {
    color: rgb(65, 54, 47);
    font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-style: normal;
    font-weight: 400;
    line-height: 1.36;
    font-size: 1.4rem;
}
```

![Image](https://github.com/user-attachments/assets/bb8f9ff8-70ab-4a5e-a503-a96f4821c9a9)

![Image](https://github.com/user-attachments/assets/6dff1f8e-3632-499d-8e16-06fb8600b7f8)
